<?php

namespace GraphQL\SchemaObject;

class UserCalloutFeatureNameEnumEnumObject extends EnumObject
{
    const GKE_CLUSTER_INTEGRATION = "GKE_CLUSTER_INTEGRATION";
    const GCP_SIGNUP_OFFER = "GCP_SIGNUP_OFFER";
    const CLUSTER_SECURITY_WARNING = "CLUSTER_SECURITY_WARNING";
    const ULTIMATE_TRIAL = "ULTIMATE_TRIAL";
    const GEO_ENABLE_HASHED_STORAGE = "GEO_ENABLE_HASHED_STORAGE";
    const GEO_MIGRATE_HASHED_STORAGE = "GEO_MIGRATE_HASHED_STORAGE";
    const CANARY_DEPLOYMENT = "CANARY_DEPLOYMENT";
    const GOLD_TRIAL_BILLINGS = "GOLD_TRIAL_BILLINGS";
    const SUGGEST_POPOVER_DISMISSED = "SUGGEST_POPOVER_DISMISSED";
    const TABS_POSITION_HIGHLIGHT = "TABS_POSITION_HIGHLIGHT";
    const THREAT_MONITORING_INFO = "THREAT_MONITORING_INFO";
    const TWO_FACTOR_AUTH_RECOVERY_SETTINGS_CHECK = "TWO_FACTOR_AUTH_RECOVERY_SETTINGS_CHECK";
    const WEB_IDE_ALERT_DISMISSED = "WEB_IDE_ALERT_DISMISSED";
    const ACTIVE_USER_COUNT_THRESHOLD = "ACTIVE_USER_COUNT_THRESHOLD";
    const BUY_PIPELINE_MINUTES_NOTIFICATION_DOT = "BUY_PIPELINE_MINUTES_NOTIFICATION_DOT";
    const PERSONAL_ACCESS_TOKEN_EXPIRY = "PERSONAL_ACCESS_TOKEN_EXPIRY";
    const SUGGEST_PIPELINE = "SUGGEST_PIPELINE";
    const CUSTOMIZE_HOMEPAGE = "CUSTOMIZE_HOMEPAGE";
    const FEATURE_FLAGS_NEW_VERSION = "FEATURE_FLAGS_NEW_VERSION";
    const REGISTRATION_ENABLED_CALLOUT = "REGISTRATION_ENABLED_CALLOUT";
    const NEW_USER_SIGNUPS_CAP_REACHED = "NEW_USER_SIGNUPS_CAP_REACHED";
    const UNFINISHED_TAG_CLEANUP_CALLOUT = "UNFINISHED_TAG_CLEANUP_CALLOUT";
    const EOA_BRONZE_PLAN_BANNER = "EOA_BRONZE_PLAN_BANNER";
    const PIPELINE_NEEDS_BANNER = "PIPELINE_NEEDS_BANNER";
    const PIPELINE_NEEDS_HOVER_TIP = "PIPELINE_NEEDS_HOVER_TIP";
    const WEB_IDE_CI_ENVIRONMENTS_GUIDANCE = "WEB_IDE_CI_ENVIRONMENTS_GUIDANCE";
    const SECURITY_CONFIGURATION_UPGRADE_BANNER = "SECURITY_CONFIGURATION_UPGRADE_BANNER";
    const CLOUD_LICENSING_SUBSCRIPTION_ACTIVATION_BANNER = "CLOUD_LICENSING_SUBSCRIPTION_ACTIVATION_BANNER";
    const TRIAL_STATUS_REMINDER_D14 = "TRIAL_STATUS_REMINDER_D14";
    const TRIAL_STATUS_REMINDER_D3 = "TRIAL_STATUS_REMINDER_D3";
    const SECURITY_CONFIGURATION_DEVOPS_ALERT = "SECURITY_CONFIGURATION_DEVOPS_ALERT";
    const PROFILE_PERSONAL_ACCESS_TOKEN_EXPIRY = "PROFILE_PERSONAL_ACCESS_TOKEN_EXPIRY";
    const TERRAFORM_NOTIFICATION_DISMISSED = "TERRAFORM_NOTIFICATION_DISMISSED";
    const SECURITY_NEWSLETTER_CALLOUT = "SECURITY_NEWSLETTER_CALLOUT";
}
