<?php

namespace GraphQL\SchemaObject;

class IssueSortEnumObject extends EnumObject
{
    const DUE_DATE_ASC = "DUE_DATE_ASC";
    const DUE_DATE_DESC = "DUE_DATE_DESC";
    const RELATIVE_POSITION_ASC = "RELATIVE_POSITION_ASC";
    const SEVERITY_ASC = "SEVERITY_ASC";
    const SEVERITY_DESC = "SEVERITY_DESC";
    const TITLE_ASC = "TITLE_ASC";
    const TITLE_DESC = "TITLE_DESC";
    const POPULARITY_ASC = "POPULARITY_ASC";
    const POPULARITY_DESC = "POPULARITY_DESC";
    const ESCALATION_STATUS_ASC = "ESCALATION_STATUS_ASC";
    const ESCALATION_STATUS_DESC = "ESCALATION_STATUS_DESC";
    const CLOSED_AT_ASC = "CLOSED_AT_ASC";
    const CLOSED_AT_DESC = "CLOSED_AT_DESC";
    const PRIORITY_ASC = "PRIORITY_ASC";
    const PRIORITY_DESC = "PRIORITY_DESC";
    const LABEL_PRIORITY_ASC = "LABEL_PRIORITY_ASC";
    const LABEL_PRIORITY_DESC = "LABEL_PRIORITY_DESC";
    const MILESTONE_DUE_ASC = "MILESTONE_DUE_ASC";
    const MILESTONE_DUE_DESC = "MILESTONE_DUE_DESC";
    const UPDATED_DESC = "UPDATED_DESC";
    const UPDATED_ASC = "UPDATED_ASC";
    const CREATED_DESC = "CREATED_DESC";
    const CREATED_ASC = "CREATED_ASC";
}
