<?php

namespace GraphQL\SchemaObject;

class ServiceTypeEnumObject extends EnumObject
{
    const APPLE_APP_STORE_SERVICE = "APPLE_APP_STORE_SERVICE";
    const ASANA_SERVICE = "ASANA_SERVICE";
    const ASSEMBLA_SERVICE = "ASSEMBLA_SERVICE";
    const BAMBOO_SERVICE = "BAMBOO_SERVICE";
    const BUGZILLA_SERVICE = "BUGZILLA_SERVICE";
    const BUILDKITE_SERVICE = "BUILDKITE_SERVICE";
    const CAMPFIRE_SERVICE = "CAMPFIRE_SERVICE";
    const CLICKUP_SERVICE = "CLICKUP_SERVICE";
    const CONFLUENCE_SERVICE = "CONFLUENCE_SERVICE";
    const CUSTOM_ISSUE_TRACKER_SERVICE = "CUSTOM_ISSUE_TRACKER_SERVICE";
    const DATADOG_SERVICE = "DATADOG_SERVICE";
    const DIFFBLUE_COVER_SERVICE = "DIFFBLUE_COVER_SERVICE";
    const DISCORD_SERVICE = "DISCORD_SERVICE";
    const DRONE_CI_SERVICE = "DRONE_CI_SERVICE";
    const EMAILS_ON_PUSH_SERVICE = "EMAILS_ON_PUSH_SERVICE";
    const EWM_SERVICE = "EWM_SERVICE";
    const EXTERNAL_WIKI_SERVICE = "EXTERNAL_WIKI_SERVICE";
    const GOOGLE_PLAY_SERVICE = "GOOGLE_PLAY_SERVICE";
    const HANGOUTS_CHAT_SERVICE = "HANGOUTS_CHAT_SERVICE";
    const HARBOR_SERVICE = "HARBOR_SERVICE";
    const IRKER_SERVICE = "IRKER_SERVICE";
    const JENKINS_SERVICE = "JENKINS_SERVICE";
    const JIRA_SERVICE = "JIRA_SERVICE";
    const MATTERMOST_SERVICE = "MATTERMOST_SERVICE";
    const MATTERMOST_SLASH_COMMANDS_SERVICE = "MATTERMOST_SLASH_COMMANDS_SERVICE";
    const MICROSOFT_TEAMS_SERVICE = "MICROSOFT_TEAMS_SERVICE";
    const PACKAGIST_SERVICE = "PACKAGIST_SERVICE";
    const PIPELINES_EMAIL_SERVICE = "PIPELINES_EMAIL_SERVICE";
    const PIVOTALTRACKER_SERVICE = "PIVOTALTRACKER_SERVICE";
    const PROMETHEUS_SERVICE = "PROMETHEUS_SERVICE";
    const PUMBLE_SERVICE = "PUMBLE_SERVICE";
    const PUSHOVER_SERVICE = "PUSHOVER_SERVICE";
    const REDMINE_SERVICE = "REDMINE_SERVICE";
    const SLACK_SERVICE = "SLACK_SERVICE";
    const SLACK_SLASH_COMMANDS_SERVICE = "SLACK_SLASH_COMMANDS_SERVICE";
    const SQUASH_TM_SERVICE = "SQUASH_TM_SERVICE";
    const TEAMCITY_SERVICE = "TEAMCITY_SERVICE";
    const TELEGRAM_SERVICE = "TELEGRAM_SERVICE";
    const UNIFY_CIRCUIT_SERVICE = "UNIFY_CIRCUIT_SERVICE";
    const WEBEX_TEAMS_SERVICE = "WEBEX_TEAMS_SERVICE";
    const YOUTRACK_SERVICE = "YOUTRACK_SERVICE";
    const ZENTAO_SERVICE = "ZENTAO_SERVICE";
}
