<?php

namespace GraphQL\SchemaObject;

class ValueStreamStageEventEnumObject extends EnumObject
{
    const ISSUE_CREATED = "ISSUE_CREATED";
    const ISSUE_FIRST_MENTIONED_IN_COMMIT = "ISSUE_FIRST_MENTIONED_IN_COMMIT";
    const ISSUE_DEPLOYED_TO_PRODUCTION = "ISSUE_DEPLOYED_TO_PRODUCTION";
    const MERGE_REQUEST_CREATED = "MERGE_REQUEST_CREATED";
    const MERGE_REQUEST_FIRST_DEPLOYED_TO_PRODUCTION = "MERGE_REQUEST_FIRST_DEPLOYED_TO_PRODUCTION";
    const MERGE_REQUEST_LAST_BUILD_FINISHED = "MERGE_REQUEST_LAST_BUILD_FINISHED";
    const MERGE_REQUEST_LAST_BUILD_STARTED = "MERGE_REQUEST_LAST_BUILD_STARTED";
    const MERGE_REQUEST_MERGED = "MERGE_REQUEST_MERGED";
    const CODE_STAGE_START = "CODE_STAGE_START";
    const ISSUE_STAGE_END = "ISSUE_STAGE_END";
    const PLAN_STAGE_START = "PLAN_STAGE_START";
}
